services:
  redis:
    container_name: commerce-redis
    image: redis:7.0.4
#    restart: always
    ports:
      - "16379:6379"
    environment:
      TZ: Asia/Seoul
    networks:
      - commerce-net

networks:
  commerce-net:
    external: true
