services:
  db:
    container_name: commerce-postgresql
    image: postgres
    ports:
      - "15432:15432"
    volumes:
      # 데이터 디렉토리 마운트
      - ./db/data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'  # 설정 파일 경로 지정
    env_file: .env
    networks:
      - commerce-net

networks:
  commerce-net: