services:
  commerce-app:
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      - commerce-net
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: single
    volumes:
      - ./logs:/app/logs

networks:
  commerce-net:
    external: true