services:
  commerce-app:
    build:
      context: ../.. # Dockerfile의 위치 지정 (현재 디렉토리)
      dockerfile: Dockerfile # 사용할 Dockerfile 명시 (기본값: Dockerfile)
#    image: commerce-app:latest
    networks:
      - commerce-net
    ports:
      - "8080" # 포트를 노출시키지 않아도 로드밸런싱엔 문제 없음
    environment:
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      replicas: 3 # 컨테이너 3개 실행 (수평 확장 가능)
#      resources:
#        limits:
#          cpus: '2'
#          memory: 2048M
  commerce-nginx:
    image: nginx:latest
    networks:
      - commerce-net
    # Nginx 컨테이너를 network_mode: host로 실행해 네트워크 계층 우회
#    network_mode: host
    ports:
      - "8081:80" # Nginx가 8081 포트에서 요청 수신
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일 매핑
    depends_on:
      - commerce-app

networks:
  commerce-net:
    external: true