server:
  tomcat:
    threads:
      max: 500
      min-spare: 20
    accept-count: 3000
    connection-timeout: 30s

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:13306/commerce
#    username: user
#    password: pw12!@
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://39.113.112.45:15432/commerce
    username: root
    password: root12!@
    hikari:
      maximum-pool-size: 300
      minimum-idle: 40
      idle-timeout: 10000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      # 컨테이너 내부에서 요청하기 때문에 내부 포트 사용해야 함
      host: commerce-redis
      port: 6379

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  file:
    path: /app/logs