server:
  address: 0.0.0.0 # 모든 네트워크 인터페이스에서 요청을 수신할 수 있도록 설정
  tomcat:
    threads:
      max: 500
      min-spare: 20
    accept-count: 3000
    connection-timeout: 30s

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:13306/commerce
#    username: user
#    password: pw12!@
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/commerce
    username: root
    password: root12!@
    hikari:
      maximum-pool-size: 300
      minimum-idle: 40
      idle-timeout: 10000
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  #    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 16379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: ./logs